{exec} = require 'child_process'

listoffiles = "coffee/axeschart.coffee coffee/job_satisfaction.coffee"

task 'build', 'build files from the src/*.coffee to lib/*.js', ->
	exec 'coffee -j job_satisfaction.js -c -o js/ ' + listoffiles, (err, stdout, stderr) ->
		throw err if err
		console.log stdout + stderr

task 'watch', 'watch for changes in files from the src/*.coffee to lib/*.js', ->
	exec 'coffee -w -j job_satisfaction.js -c -o js/ ' + listoffiles, (err, stdout, stderr) ->
		throw err if err
		console.log stdout + stderr
